goradd/goradd

pkg/bootstrap/control/form_group.go
pkg/page/control.go
pkg/page/control/form_field_wrapper.go

Fixing problem with validation. The wrapper was not getting a chance to examine the validation if the validation message changed during event processing because event processing happened after validation

bugfix-WrapperValidationProcessing

---

codegen/templates/page/panel/connector.tmpl
pkg/page/control/generator/list_select.go

Fixing a problem with select list connector for types

Select list connector fix

---

boneyard/jqui.js
codegen/templates/page/panel/edit.tmpl
codegen/templates/page/panel/list.tmpl
pkg/bootstrap/control/navbar_list.go
pkg/bootstrap/examples/panels/table.go
pkg/datetime/datetime.go
pkg/datetime/day.go
pkg/datetime/year.go
pkg/javascript/javascripter.go
pkg/page/action/callback.go
pkg/page/action/misc.go
pkg/page/control/proxy.go
pkg/page/control/table_column_base.go
pkg/page/control/textbox_date.go
pkg/page/control_base.go
pkg/page/event.go
pkg/page/event/misc.go
pkg/page/event/table_select.go
pkg/page/macros.inc.got
pkg/page/widget/megamenu.go
test/browsertest/test_controller.go
web/assets/js/goradd.js
web/examples/controls/panels/table.go
web/examples/controls/panels/table_db.go
web/examples/controls/panels/table_proxy.go

Defaulting event data to be the data sent by a trigger.
Changing ui variable to "eventData"

Default event data

---

codegen/templates/page/panel/listBaseColumnCreators.tmpl
codegen/templates/page/panel/listBaseStruct.tmpl

Minor fix for generating templates with bootstrap defaults.

Fixing package name

---

codegen/templates/page/panel/list.tmpl
internal/install/goradd-project/config/goradd.go
pkg/bootstrap/control/modal.go
pkg/page/control/dialog.go

Adding generation of dialog popup edit code

Edit dialog

---

pkg/bootstrap/control/navbar_list.go
pkg/orm/db/mysqlDescriber.go

Fix again to order of multi-column index generation

---

codegen/templates/orm/modelBase/accessors.tmpl
codegen/templates/orm/modelBase/query.tmpl
codegen/templates/page/panel/editBaseValidate.tmpl
pkg/iface/ops.go
pkg/orm/db/database.go
pkg/orm/db/index.go
pkg/page/context.go
pkg/strings/string.go
test/browsertest/test_controller.go
test/browsertest/test_form.go

Shoring up creating accessors for uniqe indexes

Index columns

---

codegen/generator/analyzers.go

Adding the ability to specify a control label text from the database comment

Control label

---

web/assets/js/goradd-testing.js
web/assets/js/goradd.js

Fixing multi-level object inheritance

regression fix

---

pkg/iface/ops.go
pkg/iface/ops_test.go

Fixing table column regression

Regression

---

pkg/bootstrap/assets/js/gr.bs.shim.js
pkg/bootstrap/control/list_radio.go
pkg/bootstrap/control/list_radiogroup.go
pkg/page/control/list_radio.go
web/assets/js/goradd.js

Fixing bootstrap radiogroup problem

Radiogroup

---

.travis.yml
pkg/html/attributes.go
pkg/page/control/data_binder.go
pkg/page/control/table.go
pkg/page/control/table_column_base.go
web/assets/js/goradd.js
web/examples/controls/panels/table_db.go

Improved js

---

pkg/bootstrap/control/navbar_list.go
pkg/bootstrap/examples/panels/table.go
pkg/page/control/column/column_texter.go
pkg/page/control/list_multiselect.go
pkg/page/control/list_select.go
pkg/page/control/list_unordered.go
pkg/page/control/repeater.go
pkg/page/control/table.go
pkg/page/widget/megamenu.go
web/examples/controls/panels/table.go

Fixing some issues with tables

Table overrides

---

codegen/templates/page/form/detailformtpl.tmpl
codegen/templates/page/form/editformtpl.tmpl
codegen/templates/page/form/listFormTpl.tmpl
internal/install/goradd-project/build/docker/zipAssets.go
internal/install/goradd-project/build/server/zipAssets.go
pkg/messageServer/ws/messenger.go
pkg/page/macros.inc.got
web/assets/js/goradd.js

Breaking change to form templates: bodyAttributes is now required.

Fixing a variety of codegen problems.

---

codegen/templates/orm/modelBase/marshalJSON.tmpl
internal/ci/db/goraddunit.mysql.sql
internal/ci/goradd-test/dbtest/association_test.go
internal/ci/goradd-test/dbtest/basicOrm_test.go
internal/ci/goradd-test/dbtest/crud_test.go
internal/ci/goradd-test/dbtest/json_test.go
internal/ci/goradd-test/dbtest/operations_test.go
internal/ci/goradd-test/dbtest/type_test.go
web/examples/db/mysql.sql
web/examples/gen/goradd/model/Project.base.go
web/examples/gen/goradd/model/node/Project.go

Fixing ability to name a local type differently than type table name

Type Name Fix

---

pkg/page/context.go
pkg/strings/rand.go

Improving context
Adding crypto string

Mods to strings and context

---

codegen/templates/orm/modelBase/accessors.tmpl
codegen/templates/orm/modelBase/pk.tmpl
codegen/templates/page/panel/detail.tmpl
codegen/templates/page/panel/editBaseReload.tmpl
pkg/orm/db/database.go

Allowing a table id to also be a foreign key for easier extensions of tables

Direct relation extension

---

codegen/templates/orm/model/stringer.tmpl
codegen/templates/page/panel/listTableRowAttributes.tmpl
doc/database.md
doc/overview.md
pkg/orm/db/database.go
pkg/orm/db/description.go
pkg/orm/db/minMax.go
pkg/orm/db/sql/mysql/mysqlDescriber.go
pkg/orm/db/sql/utils.go
pkg/orm/db/table.go

Moving options for tables and columns from the mysql level to the generic database level.
Documenting the options.
Fixing a list code generation issue.

Modifying code generation for option

---

codegen/templates/page/form/detailFormLoadControls.tmpl
pkg/auth/server.go
pkg/auth/service.go
pkg/goradd/const.go
pkg/json/number.go
pkg/page/context.go
pkg/page/control/table/column_base.go
web/app/app_base.go

Preserving client timezone in session if available

Adding client based time display to tables

---

pkg/page/control/list/checkbox.go
pkg/page/control/list/multiselect.go
pkg/page/control/list/select.go
pkg/page/form_base.go
web/examples/controls/panels/selectlist.go

Fixing checkbox list to respond correctly.
Adding ValueString function returning comma delimited values.
Putting invalidate on forms by default
Improving checkbox list test

Checkbox list fixes

---

pkg/page/control/table/column_base.go

Removing Timezone offset setting in column in favor of just showing local time. Old method could not work for local time as it would set the offset before we could get the client local time.

Showing local time

---

pkg/page/control/list/list.go
pkg/page/control/list/multiselect.go
pkg/reflect/slice.go

Expanding the ways to set multi select values

Multiselect set values

---

codegen/templates/orm/modelBase/loader.tmpl
codegen/templates/orm/modelBase/many_many_accessors.tmpl
codegen/templates/orm/modelBase/marshalBinary.tmpl
codegen/templates/orm/modelBase/marshalJSON.tmpl
codegen/templates/orm/modelBase/save.tmpl
codegen/templates/orm/modelBase/struct.tmpl
pkg/orm/db/manyManyReference.go
pkg/orm/db/model.go
web/examples/gen/goradd/model/Person.base.go
web/examples/gen/goradd/model/Project.base.go

Adding a load method for many-many associations

Many many loader

---

codegen/templates/page/form/detailFormRun.tmpl
codegen/templates/page/form/editFormAction.tmpl
codegen/templates/page/form/editFormConst.tmpl
codegen/templates/page/form/listFormConst.tmpl
codegen/templates/page/panel/listBindData.tmpl
codegen/templates/page/panel/listConst.tmpl
codegen/templates/page/panel/listCreateControls.tmpl
codegen/templates/page/panel/listTpl.tmpl
codegen/templates/page/panel/listVars.tmpl
internal/install/goradd-project/main/main.go
pkg/bootstrap/control/data_pager.go
pkg/bootstrap/examples/panels/table.go

Fixing list panel codegen issues

Codegen fixes

---

pkg/config/app.go
pkg/http/mux.go
pkg/page/control/button/file_select.go
pkg/page/control_base.go
web/assets/js/file_select.js
web/assets/js/goradd.js

Added FileSelect button for the Input type=file button.
Also fixed a regression on accessing index.html files.

FileSelect button

---

codegen/templates/page/form/detailFormConst.tmpl
codegen/templates/page/form/detailFormImport.tmpl
codegen/templates/page/form/editFormConst.tmpl
codegen/templates/page/form/editFormImport.tmpl
codegen/templates/page/form/listFormImport.tmpl
codegen/templates/page/panel/listConst.tmpl
pkg/page/control/panel.go
pkg/page/control_base.go

Adding SetTag. Fixing doc in templates.

Template improvements.

---

internal/install/goradd-project/build/app/buildLinux.go
internal/install/goradd-project/build/app/buildMac.go
internal/install/goradd-project/build/app/buildWin.go
pkg/http/cacheBuster.go
pkg/http/fileServer.go

Fixing brotli file delivery. Fixing cachebuster problem.

Fixing static file delivery issues.

---

internal/install/goradd-project/build/app/copyAssets.go
internal/install/goradd-project/config/db.go
pkg/page/control/doc.go

Doc fixes.Fixing build problem.

Minor fixes

---

pkg/bootstrap/control/tabs.go
pkg/bootstrap/control/tabs.tpl.go
pkg/bootstrap/control/tabs.tpl.got

Improving the look of a tab structure by embedding it in a card.

Surrounding tabs with a card.

---

pkg/page/action/callback.go
pkg/page/action/goradd.go
pkg/page/action/goradd_test.go
pkg/page/control/list/select.go
pkg/page/control_base.go
pkg/session/location/location.go

Refresh action

---

pkg/bootstrap/control/form_group.go
pkg/bootstrap/control/input_group.go
pkg/bootstrap/control/macros.inc.got
pkg/bootstrap/control/textbox_date.go
pkg/page/control/textbox/date.go

Fixing labels on form groups to have the form-label class.
Fixing input group to work according to Bootstrap 5 input group.

Bootstrap form fixes

---

pkg/bootstrap/control/form_group.go
pkg/bootstrap/examples/panels/forms2.tpl.go
pkg/bootstrap/examples/panels/selectlist.go
pkg/orm/db/model.go
pkg/page/context.go
pkg/page/control/form_field_wrapper.go
web/assets/js/goradd.js
web/examples/controls/panels/checkboxes.go
web/examples/controls/panels/selectlist.go
web/examples/controls/panels/table_checkbox.go
web/examples/controls/panels/textbox.go

Added encoding of goradd params to deal with web site monitors misinterpreting the data.

Encode params

---

doc/overview.md
doc/security.md
internal/install/goradd-project/config/goradd.go
internal/install/goradd-project/web/app/app.go
pkg/config/textbox.go
pkg/http/bufferedOutput.go
pkg/http/header.go
pkg/page/action/params.go
pkg/page/context.go
pkg/page/control/textbox/float.go
pkg/page/control/textbox/integer.go
pkg/page/control/textbox/textbox.go
pkg/page/form_base.go
pkg/page/page.go
pkg/page/page_manager.go
pkg/session/session.go
pkg/strings/validate.go
web/app/app_base.go
web/assets/js/goradd.js

Still to be done is a review of the logging architecture.

OWASP review and related updates
